SwapUp-dApp/Front-End-v2

src/components/custom/swap_market/open-market/OpenMarketTabContent.tsx
src/pages/ManageOpenMarketSwaps.tsx
src/pages/MySwapsPage.tsx
src/service/api/swap-market.service.ts
src/service/queries/swap-market.query.ts
src/store/swap-market/index.ts
src/store/swap-market/swap-market-helpers.ts
src/store/swap-market/swap-market-store.types.d.ts
src/types/swap-market.types.d.ts

Merging Open Swap Manage Changes to dev branch

manage open swap working copy

---

src/components/custom/swap-market/RoomFooterSide.tsx
src/index.css
src/pages/CouterOfferSwapRoom.tsx
src/pages/OpenSwapCreationRoom.tsx
src/pages/OpenSwapProposeRoom.tsx
src/pages/PrivateRoom.tsx
src/pages/ViewSwapRoom.tsx

trade summary  and select chain heading added

deedback --> dev: trade summary  and select chain heading added

---

src/components/custom/profile/EditProfileImageDialog.tsx
src/components/custom/profile/EditProfileInfoDialog.tsx
src/components/custom/profile/ProfileHeader.tsx
src/components/custom/shared/CustomAvatar.tsx
src/components/custom/shared/CustomIconButton.tsx
src/components/custom/shared/CustomOutlineButton.tsx
src/components/ui/textarea.tsx
src/lib/utils.ts
src/pages/UserProfile.tsx
src/schema/index.ts
src/store/profile/index.ts
src/store/profile/profile-helpers.ts
src/types/profile-store.types.d.ts
src/types/profile.types.d.ts

profile --> dev: profile - edit profile avatar & profile details

profile --> dev: profile - edit profile avatar & profile details

---

src/components/custom/profile/EditProfileCoverImageDialog.tsx
src/components/custom/shared/Navbar.tsx
src/components/custom/shared/ThirdWebWalletConnect.tsx
src/components/custom/shared/ToastLookCard.tsx
src/components/custom/swap-market/my-swaps/PendingSwapsTabContent.tsx
src/components/custom/swap-market/my-swaps/SwapHistoryTabContent.tsx
src/components/custom/swap-market/open-market/OpenMarketTabContent.tsx
src/layouts/MainLayout.tsx
src/lib/helpers.tsx
src/lib/utils.ts
src/pages/ManageOpenMarketSwaps.tsx
src/schema/index.ts
src/store/my-swaps/my-swaps-helpers.ts
src/store/profile/index.ts
src/store/profile/profile-helpers.ts
src/types/global.types.d.ts

profile --> dev: Fixes - re-rendering issues fixed on wallet connect & wallet switch

profile --> dev: Fixes - re-rendering issues fixed on wallet connect & wallet switch

---

.gitignore
src/pages/CounterOfferSwapRoom.tsx
src/pages/OpenSwapCreationRoom.tsx
src/pages/PrivateRoom.tsx
src/pages/ViewSwapRoom.tsx

ui-fixes --> dev: resetting room before creating or setting new data fixed

ui-fixes --> dev: resetting room before creating or setting new data fixed

---

.env

open-swap-smart-contract --> dev: new smart contract address added and tested with open swap proposal rejection

open-swap-smart-contract --> dev: new smart contract address added and tested with open swap proposal rejection

---

.env
.gitignore
package-lock.json
package.json
src/components/custom/my-swaps/PendingSwapsTabContent.tsx
src/components/custom/shared/SharingSwapCompletionOnSocialDialog.tsx
src/components/custom/swap-market/private-party/PrivateMarketTabContent.tsx
src/layouts/MainLayout.tsx
src/lib/helpers.tsx
src/pages/ViewSwapRoom.tsx
src/store/global-store/global-store-helpers.ts
src/store/global-store/index.ts
src/types/global-store.types.d.ts

subdomain --> dev: sharing swap details on twitter and warpcast (text post for now)

subdomain --> dev: sharing swap details on twitter and warpcast (text post for now)

---

src/components/custom/my-swaps/PendingSwapsTabContent.tsx
src/components/custom/profile/wallet-overview/ProfileWalletOverviewTabContent.tsx
src/components/custom/profile/wallet-overview/TokenBreakdownChart.tsx
src/components/custom/swap-market/WalletOverviewCard.tsx
src/index.css
src/pages/OpenSwapCreationRoom.tsx
src/service/api/index.ts
src/service/api/wallet.service.ts
src/store/profile/index.ts
src/store/profile/profile-helpers.ts
src/types/profile-store.types.d.ts
src/types/profile.types.d.ts
tailwind.config.js

profile --> dev: token breakdown by wallet api integration

profile --> dev: token breakdown by wallet api integration

---

.env
package-lock.json
package.json
src/components/custom/profile/wallet-overview/CollectionDetailsSection.tsx
src/components/custom/profile/wallet-overview/subdomain/ConfirmSubnameDialog.tsx
src/components/custom/profile/wallet-overview/subdomain/CreateNewSubnameDialog.tsx
src/config/config.types.d.ts
src/config/index.ts
src/lib/minting.ts
src/store/profile/index.ts
src/store/profile/profile-helpers.ts
src/types/profile.types.d.ts

subdomain-minting --> dev: namespace sdk integrated and collections section fixes
Note:
Using Sepolia for testing subname minting

subdomain-minting --> dev: namespace sdk integrated and collections section fixes

---

src/lib/walletProxy.ts

erc20-tokens-swap --> dev: swapToken to IAsset conversion issue fixed in wallet proxy file

erc20-tokens-swap --> dev: swapToken to IAsset conversion issue fixed in wallet proxy file

---

src/components/custom/swap-market/open-market/SwapParametersCard.tsx

erc20-tokens-swap --> dev: Swap parameter card nft word changed to uppercase

erc20-tokens-swap --> dev: Swap parameter card nft word changed to uppercase

---

.env

hard-fixes --> dev: backend base url updated

hard-fixes --> dev: backend base url updated

---

src/components/custom/shared/swap-sharing-process/SwapSharingOnSocialProcess.tsx
src/pages/CounterOfferSwapRoom.tsx
src/pages/OpenSwapCreationRoom.tsx
src/pages/OpenSwapProposeRoom.tsx
src/pages/ViewSwapRoom.tsx
src/service/api/swap-market.service.ts
src/service/queries/swap-market.query.ts

Swap details api updated with trade or open trade id and swap share on open swap creation

swap-sharing-update --> dev: Swap details api updated with trade or open trade id and swap share on open swap creation

---

src/pages/UserProfile.tsx
src/service/api/index.ts
src/service/api/user.service.ts
src/service/queries/user.query.ts

profile-updates --> dev: user profile latest data load on profile tab click added

profile-updates --> dev: user profile latest data load on profile tab click added

---

src/components/custom/swap-market/SwapDetailsDialog.tsx
src/components/custom/swap-market/SwapDialogSideCard.tsx
src/pages/OpenSwapCreationRoom.tsx

design-feedback --> dev: swap detail side card layout design fix

design-feedback --> dev: swap detail side card layout design fix

---

src/components/custom/profile/wallet-overview/subdomain/ConfirmSubnameDialog.tsx
src/components/custom/profile/wallet-overview/subdomain/CreateNewSubnameDialog.tsx
src/components/custom/profile/wallet-overview/subdomain/TransactionSubnameDialog.tsx
src/components/custom/thirdweb/ThirdWebWalletConnect.tsx

payment-integration --> dev: embed pay component added for testing payment

payment-integration --> dev: embed pay component added for testing payment

---

src/components/custom/profile/EditProfileCoverImageDialog.tsx
src/components/custom/profile/EditProfileImageDialog.tsx
src/components/custom/profile/wallet-overview/subdomain/ConfirmSubnameDialog.tsx
src/components/custom/profile/wallet-overview/subdomain/CreateNewSubdomainProcess.tsx
src/components/custom/thirdweb/ThirdWebWalletConnect.tsx
src/constants/defaults.ts
src/lib/thirdWebClient.ts
src/types/payments.types.d.ts

payment-integration --> dev: purchase details info & types defined, payment option moved to defaults and update avatar fixed

payment-integration --> dev: purchase details info & types defined, payment option moved to defaults and update avatar fixed

---

.env
src/config/config.types.d.ts
src/config/index.ts

payment-integration --> dev: config-refactoring: environment config structure refactoring

payment-integration --> dev: config-refactoring: environment config structure refactoring

---

src/components/custom/profile/wallet-overview/subdomain/ConfirmSubnameDialog.tsx
src/components/custom/thirdweb/ThirdWebWalletConnect.tsx
src/types/payments.types.d.ts

payment-integration --> dev: paymentTriggeredFrom check added in pay options

payment-integration --> dev: paymentTriggeredFrom check added in pay options

---

.env
src/components/custom/profile/wallet-overview/ProfileWalletOverviewTabContent.tsx
src/components/custom/profile/wallet-overview/subdomain/SubDomainMintingSection.tsx
src/components/custom/profile/wallet-overview/subdomain/SubnameListItem.tsx
src/components/custom/shared/DeleteConfirmationDialog.tsx
src/pages/PrivateRoom.tsx
src/service/api/third-party.service.ts

subname-updates --> dev: delete subname feature added using offchain delete endpoint

subname-updates --> dev: delete subname feature added using offchain delete endpoint
